### ISSUE TITLE
Популяция БД

### ISSUE THREAD

**Issue by Birdi7** [transparent-bench/Hospital-management-system#2]
Нужно создать функцию, вызов которой будет генерировать рандомные объекты, и добавлять их в базу данных. Пункт **4a** из текста задания

Что для этого нужно:
Сейчас написаны функции в формате `create_{table_name}`. Все они могут быть вызваны с нулем аргументов, и они сами создадут все что нужно (т.е. объекты для `foreign key` и прочее). Соответственно, для того, чтобы создать популяцию, нужно просто вызвать каждую из этих `create_*` рандомное число раз. Например, 20-30, или придумай сама число. 

Что важно учесть:
Нужно сделать так, чтобы все insert-statements были напечатаны на экран. Сейчас все `create_{table_name}` принимают на вход переменную `is_print`, которая отвечает за то, будут ли напечатаны insert запросы в консоль. Соответственно, тебе нужно в каждую передать `is_print=True`. Например, `create_auth(is_print=True)`. Заметь, что сигнатура функций может поменять в будущем, поэтому передавай именно в виде кварга (`create_auth(is_print=True)`), а не просто позиционным аргументом(`create_auth(True)`)

Еще: заведи аргумент `is_print` в своей функции, и передавай его в `create_*`, вместо того, чтобы кидать туда просто бул. Чтобы было легко поменять, нужен ли нам вывод, или нет. По дефолту должен быть `True`. Т.е. что-то вроде `populate_db(is_print=True)`

**Comment by Alwa0** [comment]
сделала в https://github.com/transparent-bench/Hospital-management-system/commit/37a7ec37235a10532fb1a9b73a42a3b0e09f25f6
