### ISSUE TITLE
Обновить диаграммы с phase 2

### ISSUE THREAD

**Issue by Birdi7** [transparent-bench/Hospital-management-system#4]
Мы меняли структуру данных, поэтому нужно посмотреть на таблицы, которые у нас есть сейчас, и перенести это в диаграммы
Еще можно описать словами, что в них изменилось, Муниру понравится

**Comment by Alwa0** [comment]
Добавила аттрибуты в ерд диаграмму, исправила ошибки по второй фазе. Было бы классно, если бы кто-нибудь посмотрел норм/не норм
[phase2](https://docs.google.com/document/d/1qKdWWqyR7c9rodnqTV3kHSuz_ddq80s9oU7SymkAdbg/edit#)
